// This file is generated by npm run build:icons

export type IconName =
	| "affordable"
	| "execute"
	| "on-time"
	| "premium"
	| "process-design"
	| "research"
	| "strategy"
	| "timeless"
	| "what-we-do-design";
