import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import { TailwindIndicator } from "@/components/TailwindIndicator";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="antialiased optimizeLegibility">
      <body>
        <NavBar />
        {children}
        <TailwindIndicator />
      </body>
    </html>
  );
}
