jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1

name: Semantic PR

on:
  pull_request_target:
    types:
      - edited
      - opened
      - synchronize

permissions:
  pull-requests: read
