jobs:
  sync-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1
        with:
          manifest: .github/labels.yml

name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml

  workflow_dispatch: ~
